// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PortalDocumentDataSlicesSlice = BarraLateralSlice;

/**
 * Content for Portal documents
 */
interface PortalDocumentData {
  /**
   * Slice Zone field in *Portal*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: portal.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PortalDocumentDataSlicesSlice> /**
   * Meta Title field in *Portal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: portal.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Portal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: portal.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Portal*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portal.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Portal document from Prismic
 *
 * - **API ID**: `portal`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PortalDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PortalDocumentData>,
    "portal",
    Lang
  >;

export type AllDocumentTypes = PortalDocument;

/**
 * Item in *BarraLateral → Default → Primary → GroupAplicaciones*
 */
export interface BarraLateralSliceDefaultPrimaryGroupaplicacionesItem {
  /**
   * Label field in *BarraLateral → Default → Primary → GroupAplicaciones*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: barra_lateral.default.primary.groupaplicaciones[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Icono field in *BarraLateral → Default → Primary → GroupAplicaciones*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: barra_lateral.default.primary.groupaplicaciones[].icono
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icono: prismic.ImageField<never>;
}

/**
 * Item in *BarraLateral → Default → Primary → GroupHerramientas*
 */
export interface BarraLateralSliceDefaultPrimaryGroupherramientasItem {
  /**
   * Label field in *BarraLateral → Default → Primary → GroupHerramientas*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: barra_lateral.default.primary.groupherramientas[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Icono field in *BarraLateral → Default → Primary → GroupHerramientas*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: barra_lateral.default.primary.groupherramientas[].icono
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icono: prismic.ImageField<never>;
}

/**
 * Primary content in *BarraLateral → Default → Primary*
 */
export interface BarraLateralSliceDefaultPrimary {
  /**
   * Titulo field in *BarraLateral → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: barra_lateral.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Logo field in *BarraLateral → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: barra_lateral.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * NombreEmpresa field in *BarraLateral → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: barra_lateral.default.primary.nombreempresa
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nombreempresa: prismic.KeyTextField;

  /**
   * CorreoUsuario field in *BarraLateral → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: barra_lateral.default.primary.correousuario
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  correousuario: prismic.KeyTextField;

  /**
   * LogoEmpresa field in *BarraLateral → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: barra_lateral.default.primary.logoempresa
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logoempresa: prismic.ImageField<never>;

  /**
   * LabelAplicaciones field in *BarraLateral → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: barra_lateral.default.primary.labelaplicaciones
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  labelaplicaciones: prismic.KeyTextField;

  /**
   * GroupAplicaciones field in *BarraLateral → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: barra_lateral.default.primary.groupaplicaciones[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  groupaplicaciones: prismic.GroupField<
    Simplify<BarraLateralSliceDefaultPrimaryGroupaplicacionesItem>
  >;

  /**
   * LabelHerramientas field in *BarraLateral → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: barra_lateral.default.primary.labelherramientas
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  labelherramientas: prismic.KeyTextField;

  /**
   * GroupHerramientas field in *BarraLateral → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: barra_lateral.default.primary.groupherramientas[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  groupherramientas: prismic.GroupField<
    Simplify<BarraLateralSliceDefaultPrimaryGroupherramientasItem>
  >;

  /**
   * LabelResultados field in *BarraLateral → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: barra_lateral.default.primary.labelresultados
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  labelresultados: prismic.KeyTextField;

  /**
   * LabelReportes field in *BarraLateral → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: barra_lateral.default.primary.labelreportes
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  labelreportes: prismic.KeyTextField;
}

/**
 * Default variation for BarraLateral Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BarraLateralSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BarraLateralSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BarraLateral*
 */
type BarraLateralSliceVariation = BarraLateralSliceDefault;

/**
 * BarraLateral Shared Slice
 *
 * - **API ID**: `barra_lateral`
 * - **Description**: BarraLateral
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BarraLateralSlice = prismic.SharedSlice<
  "barra_lateral",
  BarraLateralSliceVariation
>;

/**
 * Item in *Menu → Default → Primary → GroupMenu*
 */
export interface MenuSliceDefaultPrimaryGroupmenuItem {
  /**
   * LinkLabel field in *Menu → Default → Primary → GroupMenu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.default.primary.groupmenu[].linklabel
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linklabel: prismic.LinkField;

  /**
   * Label field in *Menu → Default → Primary → GroupMenu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.default.primary.groupmenu[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Primary content in *Menu → Default → Primary*
 */
export interface MenuSliceDefaultPrimary {
  /**
   * NombreEmpresa field in *Menu → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.default.primary.nombreempresa
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  nombreempresa: prismic.RichTextField;

  /**
   * LogoEmpresa field in *Menu → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.default.primary.logoempresa
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logoempresa: prismic.ImageField<never>;

  /**
   * GroupMenu field in *Menu → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.default.primary.groupmenu[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  groupmenu: prismic.GroupField<Simplify<MenuSliceDefaultPrimaryGroupmenuItem>>;

  /**
   * Logo field in *Menu → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Default variation for Menu Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MenuSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Menu*
 */
type MenuSliceVariation = MenuSliceDefault;

/**
 * Menu Shared Slice
 *
 * - **API ID**: `menu`
 * - **Description**: Menu
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuSlice = prismic.SharedSlice<"menu", MenuSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PortalDocument,
      PortalDocumentData,
      PortalDocumentDataSlicesSlice,
      AllDocumentTypes,
      BarraLateralSlice,
      BarraLateralSliceDefaultPrimaryGroupaplicacionesItem,
      BarraLateralSliceDefaultPrimaryGroupherramientasItem,
      BarraLateralSliceDefaultPrimary,
      BarraLateralSliceVariation,
      BarraLateralSliceDefault,
      MenuSlice,
      MenuSliceDefaultPrimaryGroupmenuItem,
      MenuSliceDefaultPrimary,
      MenuSliceVariation,
      MenuSliceDefault,
    };
  }
}
