// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  barra_lateral: defineAsyncComponent(() => import("./BarraLateral/index.vue")),
  menu: defineAsyncComponent(() => import("./Menu/index.vue")),
});
